package com.moer.bean;

import java.util.Date;

public class GroupMembers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.gid
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.uid
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.role_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer roleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.push_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer pushFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.create_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.update_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.expire_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer expireFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.expire_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.mute_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer muteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.mute_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Date muteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.nick_name
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.package_level
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer packageLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.stu_level
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer stuLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.channel
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.last_read_seq
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer lastReadSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.active_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Date activeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.gid
     *
     * @return the value of group_members.gid
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.gid
     *
     * @param gid the value for group_members.gid
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.uid
     *
     * @return the value of group_members.uid
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.uid
     *
     * @param uid the value for group_members.uid
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.role_flag
     *
     * @return the value of group_members.role_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getRoleFlag() {
        return roleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.role_flag
     *
     * @param roleFlag the value for group_members.role_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setRoleFlag(Integer roleFlag) {
        this.roleFlag = roleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.push_flag
     *
     * @return the value of group_members.push_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getPushFlag() {
        return pushFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.push_flag
     *
     * @param pushFlag the value for group_members.push_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setPushFlag(Integer pushFlag) {
        this.pushFlag = pushFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.create_time
     *
     * @return the value of group_members.create_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.create_time
     *
     * @param createTime the value for group_members.create_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.update_time
     *
     * @return the value of group_members.update_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.update_time
     *
     * @param updateTime the value for group_members.update_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.expire_flag
     *
     * @return the value of group_members.expire_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getExpireFlag() {
        return expireFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.expire_flag
     *
     * @param expireFlag the value for group_members.expire_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setExpireFlag(Integer expireFlag) {
        this.expireFlag = expireFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.expire_time
     *
     * @return the value of group_members.expire_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.expire_time
     *
     * @param expireTime the value for group_members.expire_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.mute_flag
     *
     * @return the value of group_members.mute_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getMuteFlag() {
        return muteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.mute_flag
     *
     * @param muteFlag the value for group_members.mute_flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setMuteFlag(Integer muteFlag) {
        this.muteFlag = muteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.mute_time
     *
     * @return the value of group_members.mute_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Date getMuteTime() {
        return muteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.mute_time
     *
     * @param muteTime the value for group_members.mute_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setMuteTime(Date muteTime) {
        this.muteTime = muteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.nick_name
     *
     * @return the value of group_members.nick_name
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.nick_name
     *
     * @param nickName the value for group_members.nick_name
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.package_level
     *
     * @return the value of group_members.package_level
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getPackageLevel() {
        return packageLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.package_level
     *
     * @param packageLevel the value for group_members.package_level
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setPackageLevel(Integer packageLevel) {
        this.packageLevel = packageLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.stu_level
     *
     * @return the value of group_members.stu_level
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getStuLevel() {
        return stuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.stu_level
     *
     * @param stuLevel the value for group_members.stu_level
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setStuLevel(Integer stuLevel) {
        this.stuLevel = stuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.channel
     *
     * @return the value of group_members.channel
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.channel
     *
     * @param channel the value for group_members.channel
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.last_read_seq
     *
     * @return the value of group_members.last_read_seq
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getLastReadSeq() {
        return lastReadSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.last_read_seq
     *
     * @param lastReadSeq the value for group_members.last_read_seq
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setLastReadSeq(Integer lastReadSeq) {
        this.lastReadSeq = lastReadSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.active_time
     *
     * @return the value of group_members.active_time
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Date getActiveTime() {
        return activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.active_time
     *
     * @param activeTime the value for group_members.active_time
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setActiveTime(Date activeTime) {
        this.activeTime = activeTime;
    }
}