package com.moer.bean;

import java.util.Date;

public class GroupInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.id
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.gid
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.owner
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.type
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.flag
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.history_days
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer historyDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.create_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.update_time
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.prices
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String prices;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.name
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.topic
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.description
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.notice
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String notice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.mute_all
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Byte muteAll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.chattype
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Byte chattype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.img
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.level
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.max
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer max;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.label
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.last_seq
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Integer lastSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.mute_free
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private Byte muteFree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.extinfo
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    private String extinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.id
     *
     * @return the value of group_info.id
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.id
     *
     * @param id the value for group_info.id
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.gid
     *
     * @return the value of group_info.gid
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.gid
     *
     * @param gid the value for group_info.gid
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.owner
     *
     * @return the value of group_info.owner
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.owner
     *
     * @param owner the value for group_info.owner
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.type
     *
     * @return the value of group_info.type
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.type
     *
     * @param type the value for group_info.type
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.flag
     *
     * @return the value of group_info.flag
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.flag
     *
     * @param flag the value for group_info.flag
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.history_days
     *
     * @return the value of group_info.history_days
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getHistoryDays() {
        return historyDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.history_days
     *
     * @param historyDays the value for group_info.history_days
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setHistoryDays(Integer historyDays) {
        this.historyDays = historyDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.create_time
     *
     * @return the value of group_info.create_time
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.create_time
     *
     * @param createTime the value for group_info.create_time
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.update_time
     *
     * @return the value of group_info.update_time
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.update_time
     *
     * @param updateTime the value for group_info.update_time
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.prices
     *
     * @return the value of group_info.prices
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getPrices() {
        return prices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.prices
     *
     * @param prices the value for group_info.prices
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setPrices(String prices) {
        this.prices = prices == null ? null : prices.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.name
     *
     * @return the value of group_info.name
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.name
     *
     * @param name the value for group_info.name
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.topic
     *
     * @return the value of group_info.topic
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.topic
     *
     * @param topic the value for group_info.topic
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.description
     *
     * @return the value of group_info.description
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.description
     *
     * @param description the value for group_info.description
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.notice
     *
     * @return the value of group_info.notice
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.notice
     *
     * @param notice the value for group_info.notice
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.mute_all
     *
     * @return the value of group_info.mute_all
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Byte getMuteAll() {
        return muteAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.mute_all
     *
     * @param muteAll the value for group_info.mute_all
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setMuteAll(Byte muteAll) {
        this.muteAll = muteAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.chattype
     *
     * @return the value of group_info.chattype
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Byte getChattype() {
        return chattype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.chattype
     *
     * @param chattype the value for group_info.chattype
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setChattype(Byte chattype) {
        this.chattype = chattype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.img
     *
     * @return the value of group_info.img
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.img
     *
     * @param img the value for group_info.img
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.level
     *
     * @return the value of group_info.level
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.level
     *
     * @param level the value for group_info.level
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.max
     *
     * @return the value of group_info.max
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.max
     *
     * @param max the value for group_info.max
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setMax(Integer max) {
        this.max = max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.label
     *
     * @return the value of group_info.label
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.label
     *
     * @param label the value for group_info.label
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.last_seq
     *
     * @return the value of group_info.last_seq
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Integer getLastSeq() {
        return lastSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.last_seq
     *
     * @param lastSeq the value for group_info.last_seq
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setLastSeq(Integer lastSeq) {
        this.lastSeq = lastSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.mute_free
     *
     * @return the value of group_info.mute_free
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public Byte getMuteFree() {
        return muteFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.mute_free
     *
     * @param muteFree the value for group_info.mute_free
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setMuteFree(Byte muteFree) {
        this.muteFree = muteFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.extinfo
     *
     * @return the value of group_info.extinfo
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public String getExtinfo() {
        return extinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.extinfo
     *
     * @param extinfo the value for group_info.extinfo
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    public void setExtinfo(String extinfo) {
        this.extinfo = extinfo == null ? null : extinfo.trim();
    }
}