package com.moer.bean;

import java.util.Date;

public class UserBlack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_black.id
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_black.initiator
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    private Integer initiator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_black.black_user
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    private Integer blackUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_black.update_user_id
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_black.update_time
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_black.create_user_id
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_black.create_time
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_black.extend1
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    private String extend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_black.extend2
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    private String extend2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_black.id
     *
     * @return the value of m_user_black.id
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_black.id
     *
     * @param id the value for m_user_black.id
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_black.initiator
     *
     * @return the value of m_user_black.initiator
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public Integer getInitiator() {
        return initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_black.initiator
     *
     * @param initiator the value for m_user_black.initiator
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public void setInitiator(Integer initiator) {
        this.initiator = initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_black.black_user
     *
     * @return the value of m_user_black.black_user
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public Integer getBlackUser() {
        return blackUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_black.black_user
     *
     * @param blackUser the value for m_user_black.black_user
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public void setBlackUser(Integer blackUser) {
        this.blackUser = blackUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_black.update_user_id
     *
     * @return the value of m_user_black.update_user_id
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_black.update_user_id
     *
     * @param updateUserId the value for m_user_black.update_user_id
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_black.update_time
     *
     * @return the value of m_user_black.update_time
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_black.update_time
     *
     * @param updateTime the value for m_user_black.update_time
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_black.create_user_id
     *
     * @return the value of m_user_black.create_user_id
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_black.create_user_id
     *
     * @param createUserId the value for m_user_black.create_user_id
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_black.create_time
     *
     * @return the value of m_user_black.create_time
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_black.create_time
     *
     * @param createTime the value for m_user_black.create_time
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_black.extend1
     *
     * @return the value of m_user_black.extend1
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_black.extend1
     *
     * @param extend1 the value for m_user_black.extend1
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_black.extend2
     *
     * @return the value of m_user_black.extend2
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_black.extend2
     *
     * @param extend2 the value for m_user_black.extend2
     *
     * @mbggenerated Wed Jan 09 14:03:38 CST 2019
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }
}