package com.moer.dao.mysql;

import com.moer.bean.GroupMembers;
import com.moer.common.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
public interface GroupMembersMapper extends Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int insert(GroupMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int insertSelective(GroupMembers record);

    List<GroupMembers> selectBySelective(@Param("record") GroupMembers record);
}