package com.moer.dao.mysql;

import com.moer.bean.GroupHistoryMessage;
import com.moer.bean.GroupHistoryMessageWithBLOBs;
import com.moer.common.Mapper;

public interface GroupHistoryMessageMapper extends Mapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_history_message
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int deleteByPrimaryKey(String mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_history_message
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int insert(GroupHistoryMessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_history_message
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int insertSelective(GroupHistoryMessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_history_message
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    GroupHistoryMessageWithBLOBs selectByPrimaryKey(String mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_history_message
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int updateByPrimaryKeySelective(GroupHistoryMessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_history_message
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(GroupHistoryMessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_history_message
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int updateByPrimaryKey(GroupHistoryMessage record);
}