package com.moer.dao.mysql;

import com.moer.bean.GroupMembers;

public interface GroupMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int insert(GroupMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int insertSelective(GroupMembers record);
}