package com.moer.dao.mysql;

import com.moer.bean.GroupInfo;

public interface GroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int insert(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int insertSelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    GroupInfo selectByPrimaryKey(Integer id);
    GroupInfo selectByGid(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int updateByPrimaryKeySelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbggenerated Mon Jun 11 14:24:09 CST 2018
     */
    int updateByPrimaryKey(GroupInfo record);
}